### ISSUE TITLE
Jsonx.formatCaseClass[A] should return OFormat not Format

### ISSUE THREAD

**Issue by jmess4** [xdotai/play-json-extensions#32]
Play 2.5 macros use OFormat not Format. 

Something like `implicit val sampleFormt = Jsonx.formatCaseClass[Sample]` will compile but fail at runtime to do any conversions.

**Comment by cvogt** [comment]
could you give me a code sample to reproduce this? Then I'll turn it into a test and release a fix.

**Comment by apatzer** [comment]
@jmess4 is correct, Play-Json 2.5+ uses OWrites[T] and OFormat[T]. I'm running into a similar issue on any case class, and further issue now that I've bumped up to
`"com.typesafe.play" %% "play-json" % "2.6.0-M3"` which has built-in support for defaults (but not 22+ fields).

**Comment by clamothe** [comment]
I agree. For type safety, I'd prefer formatCaseClass to explicitly return an OFormat, if this is the underlying type. This way, I don't need to call jsVal.asInstanceOf[JsObject] for it's value.

**Comment by cvogt** [comment]
could someone create a PR ideally with a filing test case? I don't completely understand the issue or solution. Haven't been following 2.5 closely. Happy to get a new version out asap after.

**Comment by clamothe** [comment]
I'll do so if I can find the time. Thanks for the quick reply.

Sorry if this is pedantic. I'd rather be specific than not explain it
sufficiently.
OFormat is a Format restricted to reading and writing JsObjects (one case
of JsValue). If formatCaseClass in fact creates a Format that always
reads/writes JsObjects rather than another JsValue such as JsString, it
could return OFormat instead. Consumers of formatCaseClass would then be
able to assume in a type-safe manner that it reads/writes JsObjects. We
have in our code an OFormat implementation that wraps formatCaseClass,
providing some customized serialization. Since formatCaseClass returns a
JsValue, our writes method looks like:

override def writes(o: T): JsObject = writer.writes(o).asInstanceOf[JsObject]

**Comment by clamothe** [comment]
.. and if formatCaseClass doesn't in fact always read/write JsObjects, then
our code would break at runtime if a non-JsObject is returned! Hence if we
can make this assumption in a type-safe manner, it's best.

**Comment by clamothe** [comment]
https://github.com/xdotai/play-json-extensions/pull/35
